name: 'Next Page Mapper'
description: 'This action takes the git diff between two branches, generates a JSON file with the affected page/views'
author: 'Alejandro Varela'

branding:
  icon: 'activity'
  color: 'red'

inputs:

  modified_files:
    description: 'The list of modified files in the git diff.'
    required: true
  
  pages_to_check:
    description: 'The list of pages to check in the git diff.'
    required: true
  
  host_output:
    description: 'The host output file.'
    required: false
    default: 'http://localhost:3000/'

outputs:

  affected_pages:
    description: 'The list of affected pages.'

runs:
  using: 'node20'
  main: 'dist/index.js'
